// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type GetUserInfoRequest struct {
	Id int64 `path:"id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token    string            `json:"token"`
	UserInfo *UserInfoResponse `json:"user_info"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UpdateUserInfoRequest struct {
	Id       int64  `path:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
}

type GameRecommendation struct {
	Id         string   `json:"id"`
	Title      string   `json:"title"`
	CoverImage string   `json:"cover_image"`
	Genres     []string `json:"genres"`
	Platforms  []string `json:"platforms"`
	Score      float64  `json:"score"`
	Tags       []string `json:"tags"`
}

type GetUserRecommendationsRequest struct {
	Id     int64  `path:"id"`
	Genres string `form:"genres,optional"`
	Limit  int64  `form:"limit,default=5"`
}
