// Code generated by goctl. DO NOT EDIT.
package types

type Guide struct {
	Id          int64    `json:"id"`
	GameId      string   `json:"game_id"`
	GameTitle   string   `json:"game_title"`
	Title       string   `json:"title"`
	Content     string   `json:"content"`
	Format      string   `json:"format,omitempty"`
	Summary     string   `json:"summary"`
	CoverImage  string   `json:"cover_image"`
	AuthorId    int64    `json:"author_id"`
	AuthorName  string   `json:"author_name"`
	Tags        []string `json:"tags"`
	Views       int      `json:"views"`
	Likes       int      `json:"likes"`
	IsPublished bool     `json:"is_published"`
	CreatedAt   string   `json:"created_at"`
	UpdatedAt   string   `json:"updated_at"`
}

type CreateGuideRequest struct {
	GameId     string   `json:"game_id"`
	Title      string   `json:"title"`
	Content    string   `json:"content"`
	Format     string   `json:"format,optional"`
	Summary    string   `json:"summary,optional"`
	CoverImage string   `json:"cover_image,optional"`
	Tags       []string `json:"tags,optional"`
}

type CreateGuideResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    Guide  `json:"data"`
}

type UpdateGuideRequest struct {
	Id         int64    `path:"id"`
	Title      string   `json:"title,optional"`
	Content    string   `json:"content,optional"`
	Format     string   `json:"format,optional"`
	Summary    string   `json:"summary,optional"`
	CoverImage string   `json:"cover_image,optional"`
	Tags       []string `json:"tags,optional"`
}

type UpdateGuideResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    Guide  `json:"data"`
}

type ListGuidesRequest struct {
	GameId   string `form:"game_id,optional"`
	AuthorId int64  `form:"author_id,optional"`
	Tag      string `form:"tag,optional"`
	Keyword  string `form:"keyword,optional"`
	Sort     string `form:"sort,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
}

type ListGuidesResponse struct {
	Code    int     `json:"code"`
	Message string  `json:"message"`
	Data    []Guide `json:"data"`
	Total   int     `json:"total"`
	Page    int     `json:"page"`
}

type GetGuideRequest struct {
	Id int64 `path:"id"`
}

type GetGuideResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    Guide  `json:"data"`
}

type PublishGuideRequest struct {
	Id int64 `path:"id"`
}

type PublishGuideResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LikeGuideRequest struct {
	Id int64 `path:"id"`
}

type LikeGuideResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Likes   int    `json:"likes"`
}

type FavoriteGuideRequest struct {
	Id int64 `path:"id"`
}

type FavoriteGuideResponse struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	Favorited bool   `json:"favorited"`
	Count     int64  `json:"count"`
}

type ListFavoritesRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type Comment struct {
	Id         int64  `json:"id"`
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
	UserId     int64  `json:"user_id"`
	UserName   string `json:"user_name"`
	Content    string `json:"content"`
	ParentId   int64  `json:"parent_id,omitempty"`
	ReplyToId  int64  `json:"reply_to_id,omitempty"`
	Likes      int    `json:"likes"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type CreateCommentRequest struct {
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
	Content    string `json:"content"`
	ParentId   int64  `json:"parent_id,optional"`
	ReplyToId  int64  `json:"reply_to_id,optional"`
}

type CreateCommentResponse struct {
	Code    int     `json:"code"`
	Message string  `json:"message"`
	Data    Comment `json:"data"`
}

type ListCommentsRequest struct {
	TargetType string `form:"target_type"`
	TargetId   int64  `form:"target_id"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"page_size,default=20"`
}

type ListCommentsResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    []Comment `json:"data"`
	Total   int       `json:"total"`
	Page    int       `json:"page"`
}

type DeleteCommentRequest struct {
	Id int64 `path:"id"`
}

type DeleteCommentResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LikeCommentRequest struct {
	Id int64 `path:"id"`
}

type LikeCommentResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Likes   int    `json:"likes"`
}
