// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// 手工改动：POST /games 追加 JWT 认证中间件（写接口保护），其余公开路由不变。

package handler

import (
	"net/http"

	"github.com/tappi/tappi/services/game-catalog/internal/svc"
	"github.com/tappi/tappi/services/game-catalog/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/games",
			Handler: ListGamesHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/:id",
			Handler: GetGameDetailHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/featured",
			Handler: GetFeaturedGamesHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/recommendations",
			Handler: GetRecommendationsHandler(serverCtx),
		},
	})

	// 受保护路由：写接口需要 Bearer 令牌（由 user-service 签发）
	server.AddRoutes(
		rest.WithMiddleware(middleware.AuthMiddleware(serverCtx), rest.Route{
			Method:  http.MethodPost,
			Path:    "/games",
			Handler: CreateGameHandler(serverCtx),
		}),
	)
}
