// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/tappi/tappi/services/game-catalog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/games",
			Handler: ListGamesHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/:id",
			Handler: GetGameDetailHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/games",
			Handler: CreateGameHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/featured",
			Handler: GetFeaturedGamesHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/recommendations",
			Handler: GetRecommendationsHandler(serverCtx),
		},
	})
}
