// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommonResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CreatePostReq struct {
	TopicId int64    `json:"topic_id"`
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Images  []string `json:"images,omitempty"`
	Type    string   `json:"type,omitempty"` // 默认 discussion
	Tags    []string `json:"tags,omitempty"`
}

type CreateTopicReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon,omitempty"`
	CoverImage  string `json:"cover_image,omitempty"`
}

type DeletePostReq struct {
	Id int64 `path:"id"`
}

type FollowTopicReq struct {
	TopicId int64 `path:"topic_id"`
}

type FollowUserReq struct {
	UserId int64 `path:"user_id"`
}

type FollowingResp struct {
	Topics []Topic `json:"topics"`
}

type GetPostReq struct {
	Id int64 `path:"id"`
}

type GetPostsReq struct {
	TopicId  int64  `form:"topic_id,optional"`
	AuthorId int64  `form:"author_id,optional"`
	Type     string `form:"type,optional"`
	Status   string `form:"status,optional"`
	IsHot    bool   `form:"is_hot,optional"`
	Limit    int64  `form:"limit,optional,default=20"`
	Offset   int64  `form:"offset,optional,default=0"`
}

type GetTopicReq struct {
	Id int64 `path:"id"`
}

type GetTopicsReq struct {
	Keyword    string `form:"keyword,optional"`
	IsOfficial bool   `form:"is_official,optional"`
	Limit      int64  `form:"limit,optional,default=20"`
	Offset     int64  `form:"offset,optional,default=0"`
}

type LikeReq struct {
	TargetType string `json:"target_type"` // post/comment
	TargetId   int64  `json:"target_id"`
}

type Post struct {
	Id           int64    `json:"id"`
	TopicId      int64    `json:"topic_id"` // 所属话题ID
	AuthorId     int64    `json:"author_id"`
	AuthorName   string   `json:"author_name,omitempty"`
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Images       []string `json:"images,omitempty"` // 图片URL列表
	Type         string   `json:"type"`             // 类型：discussion/question/share
	Tags         []string `json:"tags,omitempty"`
	ViewCount    int64    `json:"view_count"`
	LikeCount    int64    `json:"like_count"`
	CommentCount int64    `json:"comment_count"`
	ShareCount   int64    `json:"share_count"`
	IsPinned     bool     `json:"is_pinned"` // 是否置顶
	IsHot        bool     `json:"is_hot"`    // 是否热门
	Status       string   `json:"status"`    // draft/published/deleted
	CreatedAt    string   `json:"created_at"`
	UpdatedAt    string   `json:"updated_at"`
}

type PostResp struct {
	Post Post `json:"post"`
}

type PostsResp struct {
	Posts []Post `json:"posts"`
	Total int64  `json:"total"`
}

type Topic struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Icon          string `json:"icon,omitempty"`
	CoverImage    string `json:"cover_image,omitempty"`
	PostCount     int64  `json:"post_count"`
	FollowerCount int64  `json:"follower_count"`
	IsOfficial    bool   `json:"is_official"` // 是否官方话题
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type TopicResp struct {
	Topic Topic `json:"topic"`
}

type TopicsResp struct {
	Topics []Topic `json:"topics"`
	Total  int64   `json:"total"`
}

type UpdatePostReq struct {
	Title   string   `json:"title,omitempty"`
	Content string   `json:"content,omitempty"`
	Images  []string `json:"images,omitempty"`
	Tags    []string `json:"tags,omitempty"`
}
