// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommonResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CreatePostReq struct {
	TopicId int64    `json:"topic_id"`
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Images  []string `json:"images,optional"`
	Type    string   `json:"type,optional"` // 默认 discussion
	Tags    []string `json:"tags,optional"`
}

type CreateTopicReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon,optional"`
	CoverImage  string `json:"cover_image,optional"`
}

type DeletePostReq struct {
	Id int64 `path:"id"`
}

type FollowTopicReq struct {
	TopicId int64 `path:"topic_id"`
}

type FollowUserReq struct {
	UserId int64 `path:"user_id"`
}

type FollowingResp struct {
	Topics []Topic `json:"topics"`
}

type FollowingUsersResp struct {
	UserIds []int64 `json:"user_ids"`
}

type GetFollowedPostsReq struct {
	Limit  int64 `form:"limit,optional,default=20"`
	Offset int64 `form:"offset,optional,default=0"`
}

// GetLikedPostsReq 我的点赞（M3 个人中心）：点赞关系 join 帖子，
// 点赞时间倒序分页，与关注流同款分页参数语义。
type GetLikedPostsReq struct {
	Limit  int64 `form:"limit,optional,default=20"`
	Offset int64 `form:"offset,optional,default=0"`
}

// 帖子评论（单层，parent_id 预留嵌套扩展）：reply_to_author_name 由服务端
// 从被回复评论冗余，客户端直接展示「回复 @xxx」。
type Comment struct {
	Id                int64  `json:"id"`
	PostId            int64  `json:"post_id"`
	AuthorId          int64  `json:"author_id"`
	AuthorName        string `json:"author_name"`
	Content           string `json:"content"`
	ParentId          int64  `json:"parent_id,omitempty"`
	ReplyToAuthorName string `json:"reply_to_author_name,omitempty"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type CreateCommentReq struct {
	Id       int64  `path:"id"`
	Content  string `json:"content"`
	ParentId int64  `json:"parent_id,optional"`
}

type ListCommentsReq struct {
	Id     int64 `path:"id"`
	Limit  int64 `form:"limit,optional,default=50"`
	Offset int64 `form:"offset,optional,default=0"`
}

type DeleteCommentReq struct {
	// 帖子路径 + 评论 id 双段：网关上 content-service 已占 /api/v1/comments/:id，
	// 社区评论删除挂在帖子子资源下避免跨服务路由冲突。
	Id        int64 `path:"id"`
	CommentId int64 `path:"cid"`
}

type CommentResp struct {
	Comment *Comment `json:"comment"`
}

type CommentsResp struct {
	Comments []*Comment `json:"comments"`
	Total    int64      `json:"total"`
}

// 站内通知（点赞/评论/回复/关注四类）：content 冗余行为摘要供列表直接展示，
// target_id 指向帖子/评论/被关注用户；is_read 由 read-all 端点批量翻转。
type Notification struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"user_id"`
	ActorId   int64  `json:"actor_id"`
	ActorName string `json:"actor_name"`
	Type      string `json:"type"` // like_post/comment_post/reply_comment/follow_user
	TargetId  int64  `json:"target_id"`
	Content   string `json:"content"`
	IsRead    bool   `json:"is_read"`
	CreatedAt string `json:"created_at"`
}

type ListNotificationsReq struct {
	Limit  int64 `form:"limit,optional,default=20"`
	Offset int64 `form:"offset,optional,default=0"`
}

type NotificationsResp struct {
	Notifications []*Notification `json:"notifications"`
	Total         int64           `json:"total"`
}

type UnreadCountResp struct {
	Count int64 `json:"count"`
}

// 举报（内容审核）：target_type 为 post/comment；status 流转
// pending → dismissed（驳回）/ resolved（处置，内容已移除）。
type Report struct {
	Id         int64  `json:"id"`
	ReporterId int64  `json:"reporter_id"`
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
	Reason     string `json:"reason"`
	Status     string `json:"status"`
	HandledBy  int64  `json:"handled_by,omitempty"`
	CreatedAt  string `json:"created_at"`
	HandledAt  string `json:"handled_at,omitempty"`
}

type ReportPostReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason,optional"`
}

type ListReportsReq struct {
	Status string `form:"status,optional"`
	Limit  int64  `form:"limit,optional,default=20"`
	Offset int64  `form:"offset,optional,default=0"`
}

type HandleReportReq struct {
	Id     int64  `path:"id"`
	Action string `json:"action"` // dismiss/resolve
}

type ReportsResp struct {
	Reports []*Report `json:"reports"`
	Total   int64     `json:"total"`
}

type GetPostReq struct {
	Id int64 `path:"id"`
}

type GetPostsReq struct {
	TopicId  int64  `form:"topic_id,optional"`
	AuthorId int64  `form:"author_id,optional"`
	Type     string `form:"type,optional"`
	Status   string `form:"status,optional"`
	IsHot    bool   `form:"is_hot,optional"`
	Limit    int64  `form:"limit,optional,default=20"`
	Offset   int64  `form:"offset,optional,default=0"`
}

type GetTopicReq struct {
	Id int64 `path:"id"`
}

type GetTopicsReq struct {
	Keyword    string `form:"keyword,optional"`
	IsOfficial bool   `form:"is_official,optional"`
	Limit      int64  `form:"limit,optional,default=20"`
	Offset     int64  `form:"offset,optional,default=0"`
}

type LikePostReq struct {
	Id int64 `path:"id"`
}

type LikeReq struct {
	TargetType string `json:"target_type"` // post/comment
	TargetId   int64  `json:"target_id"`
}

type Post struct {
	Id           int64    `json:"id"`
	TopicId      int64    `json:"topic_id"` // 所属话题ID
	AuthorId     int64    `json:"author_id"`
	AuthorName   string   `json:"author_name,omitempty"`
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Images       []string `json:"images,omitempty"` // 图片URL列表
	Type         string   `json:"type"`             // 类型：discussion/question/share
	Tags         []string `json:"tags,omitempty"`
	ViewCount    int64    `json:"view_count"`
	LikeCount    int64    `json:"like_count"`
	CommentCount int64    `json:"comment_count"`
	ShareCount   int64    `json:"share_count"`
	IsPinned     bool     `json:"is_pinned"` // 是否置顶
	IsHot        bool     `json:"is_hot"`    // 是否热门
	Status       string   `json:"status"`    // draft/published/deleted
	CreatedAt    string   `json:"created_at"`
	UpdatedAt    string   `json:"updated_at"`
}

type PostResp struct {
	Post Post `json:"post"`
}

type PostsResp struct {
	Posts []Post `json:"posts"`
	Total int64  `json:"total"`
}

type SharePostReq struct {
	Id int64 `path:"id"`
}

type Topic struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Icon          string `json:"icon,omitempty"`
	CoverImage    string `json:"cover_image,omitempty"`
	PostCount     int64  `json:"post_count"`
	FollowerCount int64  `json:"follower_count"`
	IsOfficial    bool   `json:"is_official"` // 是否官方话题
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type TopicResp struct {
	Topic Topic `json:"topic"`
}

type TopicsResp struct {
	Topics []Topic `json:"topics"`
	Total  int64   `json:"total"`
}

type UpdatePostReq struct {
	Id      int64    `path:"id"`
	Title   string   `json:"title,optional"`
	Content string   `json:"content,optional"`
	Images  []string `json:"images,optional"`
	Tags    []string `json:"tags,optional"`
}
