// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/tappi/tappi/services/api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/auth/login",
			Handler: LoginHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/games/featured",
			Handler: FeaturedGamesHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/users/:id/recommendations",
			Handler: UserRecommendationsHandler(serverCtx),
		},
	})
}
