// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	comment "github.com/tappi/tappi/services/community/internal/handler/comment"
	follow "github.com/tappi/tappi/services/community/internal/handler/follow"
	post "github.com/tappi/tappi/services/community/internal/handler/post"
	topic "github.com/tappi/tappi/services/community/internal/handler/topic"
	"github.com/tappi/tappi/services/community/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/users/:user_id/follow",
					Handler: follow.FollowUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/:user_id/follow",
					Handler: follow.UnfollowUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/following",
					Handler: follow.GetFollowingUsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/posts",
					Handler: post.CreatePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/posts/:id",
					Handler: post.UpdatePostHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/posts/:id",
					Handler: post.DeletePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/posts/:id/like",
					Handler: post.LikePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/posts/:id/share",
					Handler: post.SharePostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/posts/followed",
					Handler: post.GetFollowedPostsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/likes",
					Handler: post.GetLikedPostsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/posts/:id/comments",
					Handler: comment.CreateCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/posts/:id/comments/:cid",
					Handler: comment.DeleteCommentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/posts/:id/comments",
				Handler: comment.ListCommentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: post.GetPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: post.GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/hot",
				Handler: post.GetHotPostsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/topics",
					Handler: topic.CreateTopicHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/topics/:topic_id/follow",
					Handler: topic.FollowTopicHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/topics/:topic_id/follow",
					Handler: topic.UnfollowTopicHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/topics/following",
					Handler: topic.GetFollowingTopicsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/topics",
				Handler: topic.GetTopicsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topics/:id",
				Handler: topic.GetTopicHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
