// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/tappi/tappi/services/content-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/guides",
				Handler: CreateGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/guides/:id",
				Handler: UpdateGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/guides/favorites",
				Handler: ListFavoritesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/guides/:id",
				Handler: GetGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/guides",
				Handler: ListGuidesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/guides/:id/publish",
				Handler: PublishGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/guides/:id/like",
				Handler: LikeGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/guides/:id/favorite",
				Handler: FavoriteGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/guides/:id/favorite",
				Handler: UnfavoriteGuideHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/guides/:id/favorite",
				Handler: GetFavoriteStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comments",
				Handler: CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: ListCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/comments/:id",
				Handler: DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comments/:id/like",
				Handler: LikeCommentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
